export const MOBILE_CONFIG = {
    USER_DETAIL: "USER_DETAIL",
    LANGUAGE_ID: "LANGUAGE_ID",
    LANGUAGE_LIST: "LANGUAGE_LIST",
    DEFAULT_LANGUAGE_ID: "DEFAULT_LANGUAGE_ID",
    TOKEN_STATUS: "TOKEN_STATUS",
    ACCESS_TOKEN: "ACCESS_TOKEN",
    REFRESH_TOKEN: "REFRESH_TOKEN",
    DB_KEY: "DB_KEY",
    PASS_CODE: "PASS_CODE",
    IS_FIRST_TIME: "IS_FIRST_TIME"
};

export const MOBILE_SCREENS = {
    SPLASH: "SPLASH",
    ERROR_SCREEN: "ERROR_SCREEN",
    HOME: "HOME",
    STUDENTS: "STUDENTS",
    ADD_EDIT_STUDENT: "ADD_EDIT_STUDENT",
    LANGUAGE: "LANGUAGE",
    PASSCODE: "PASSCODE",
    OTP_CODE: "OTP_CODE",
    SIGNIN: "SIGNIN",
    SIGNUP: "SIGNUP",
    SETTINGS: "SETTINGS",
    OTP_USER: "OTP_USER",
    FORGOT_PASSWORD:"FORGOT_PASSWORD"
}

export const PICKER_TYPE = {
    CIRCLE: "CIRCLE",
    RECTANGLE: "RECTANGLE"
}