export const SMS_CONSTANTS = {
    SMS_USER_NAME: "SMS_USER_NAME",
    SMS_API_KEY: "SMS_API_KEY",
    SMS_SENDER_ID: "SMS_SENDER_ID",
    SMS_TID: "SMS_TID",
    SMS_NUMBER: "SMS_NUMBER",
    SMS_MESSAGE: "SMS_MESSAGE",
    USER_OTP: "USER_OTP"
}

export const SMS_API = ``;

export const SECRET_KEYS = {
    AWS_ACCESS_ID: "AWS_ACCESS_ID",
    AWS_SECRET_KEY: "AWS_SECRET_KEY",
    AWS_REGION: "AWS_REGION"
};

export const AWS_SM_SECRET_STRING = "SecretString";

export const SECRET_DETAILS: any = [];
//TODO: remove this before deployment
SECRET_DETAILS[SECRET_KEYS.AWS_ACCESS_ID] = "";
SECRET_DETAILS[SECRET_KEYS.AWS_SECRET_KEY] = "";
SECRET_DETAILS[SECRET_KEYS.AWS_REGION] = "";
SECRET_DETAILS[SMS_CONSTANTS.SMS_USER_NAME] = "";
SECRET_DETAILS[SMS_CONSTANTS.SMS_API_KEY] = "";
SECRET_DETAILS[SMS_CONSTANTS.SMS_SENDER_ID] = "";
SECRET_DETAILS[SMS_CONSTANTS.SMS_TID] = "";